### ISSUE TITLE
Thoughts about the new Debian jessie bootstrap tarball

### ISSUE THREAD

**Issue by npf** [grid5000/environments-recipes#13]
The last Debian Jessie bootstrap tarball provided by the kameleon team to build g5k environment comes with a set of additional packages compared to the old version (2015). One of the reason is that the kameleon developer changed from a debootstrap generation to a "more conventional" netinstall/preseed installation.

Currently, the following additional packages are installed:
+acpi
+acpi-support-base
+acpid
+busybox
+bzip2
+console-setup
+console-setup-linux
+dictionaries-common
+discover
+discover-data
+dmeventd
+eject
+emacsen-common
+gettext-base
+grub-common
+grub-pc
+grub-pc-bin
+grub2-common
+iamerican
+ibritish
+ienglish-common
+installation-report
+ispell
+kbd
+keyboard-configuration
+krb5-locales
+laptop-detect
+libalgorithm-c3-perl
+libarchive-extract-perl
+libasprintf0c2:amd64
+libcgi-fast-perl
+libcgi-pm-perl
+libclass-c3-perl
+libclass-c3-xs-perl
+libcpan-meta-perl
+libdata-optlist-perl
+libdata-section-perl
+libdevmapper-event1.02.1:amd64
+libdiscover2
+libexpat1:amd64
+libfcgi-perl
+libfreetype6:amd64
+libfuse2:amd64
+liblog-message-perl
+liblog-message-simple-perl
+liblvm2cmd2.02:amd64
+libmodule-build-perl
+libmodule-pluggable-perl
+libmodule-signature-perl
+libmro-compat-perl
+libopts25:amd64
+libpackage-constants-perl
+libparams-util-perl
+libpci3:amd64
+libpng12-0:amd64
+libpod-latex-perl
+libpod-readme-perl
+libreadline5:amd64
+libregexp-common-perl
+libsoftware-license-perl
+libsub-exporter-perl
+libsub-install-perl
+libterm-ui-perl
+libtext-soundex-perl
+libtext-template-perl
+libx11-6:amd64
+libx11-data
+libxau6:amd64
+libxcb1:amd64
+libxdmcp6:amd64
+libxext6:amd64
+libxmuu1:amd64
+lvm2
+ncurses-term
+ntp
+os-prober
+pciutils
+perl
+perl-modules
+rename
+rsync
+sudo
+task-english
+tcpd
+ucf
+util-linux-locales
+wamerican
+xauth
+xkb-data

The preseed file in use can be found here:
https://github.com/oar-team/kameleon-recipes/blob/refactor/steps/data/debian-jessie-preseed.cfg
Some remarks:
- Tasksel is set to none, but the english task seem selected however.
- Some packages are manually selected: openssh-server ntp acpid  sudo bzip2 rsync
- Time setting is ntp
- Disk setting is LVM
- Grub is installed

Any thoughts ? 
- Suggestions could be to try to remove lvm and ntp from the preseed.
- Maybe acpid ?

Some of the additional packages may be needed for the generation to function -> must be added, but could be removed before exporting maybe...
I don't see an obvious way of preventing the english task from being installed.

**Comment by npf** [comment]
add @mickours to the loop

**Comment by lnussbaum** [comment]
Il faudrait regarder si debfoster permet de supprimer simplement les paquets supplémentaires. avec qqchose comme debfoster -o MaxPriority=standard par exemple

**Comment by lnussbaum** [comment]
il y a une discussion démarrant à https://lists.debian.org/debian-cloud/2016/08/msg00015.html sur les outils de génération d'images pour le cloud

**Comment by npf** [comment]
I rolled back the debian8 recipe to use debootstrap (https://github.com/oar-team/kameleon-recipes/tree/refactor ->from_scratch/debian8.yaml). 
This is in the refactor branch which is soon to become the master branch.
Release tag: https://github.com/oar-team/kameleon-recipes/releases/tag/debian8_20160921181636

Packages installed are the same as in the tarball from 2015, with some version changes of course. The resulting tarball has just a bit more files (side effects of the packages versions upgrade).

G5K recipes can give a try to: http://kameleon.imag.fr/rootfs/x86_64/debian8_20160921181636.tar.xz (along with its cache and sha1sums), capabilities are ok.

**Comment by lnussbaum** [comment]
to clarify, does this include the capabilities fix?

**Comment by npf** [comment]
yes
