### ISSUE TITLE
Add the postinstall in the recipes

### ISSUE THREAD

**Issue by npf** [grid5000/environments-recipes#2]
Postinstall files/script could actually be stored in the environment tarball, e.g. in /root/postinstall, instead of in another tarball like now (that's currently useful to reuse a postinstall with several environemnet, but with generating environment with kameleon, sharing will happen ahead).

They should comply to the interface/data provides by kadeploy and the prepost (need work here to uniformize).

Kadeploy would not need changes, since its current mechanism for postinstall would just call the script which are embedded in the tarball.

In the end: the kameleon exported output should provide:
- a tarball with all the smart/custom bits in it
- an description env file
- a postintall that is only a wrapper which calls the embedded scripts inside the tarball

That way it would be easy to take that tarball to customize both the system and the post-installation scripts, as suggested in issue #1.

**Comment by dmargery** [comment]
So the roles would be
- the technical team maintains on each site what we now call a prepost. This script is not allowed to touch ou put data on the disk being deployed, but makes data available to the post-install
- the technical team maintains the kameleon recipe to generate the post-install script that is part of the image and that will be run by Kadeploy3 to adapt the on-disk image to the specific site/hardware it is deployed on
- a generic post-install is generated and made available on all sites. This script only calls the post-install script that is part of the image, and will probably seldom change. It would also not be allowed to change on disk-data

The downside of this approach is that it will be difficult to cleanly update the post-installation script. We would need to look into why we changed the post-install script this last year to see if the use cases are well covered with this architectural change.

Of course, with a well known location of the post-installation script, providing a tool to allow users to update it is trivial. We might even might be able, with the cooperation of Kadeploy3, to make checks on a image that people want to deploy so to either to cleanly fail if it is using an outdated post-install embedded in the image or automatically update it.

David

**Comment by npf** [comment]
Yes about the roles. The 3rd one could actually be seen as just a glue allowing compatibility with kadeploy. A new version of kadeploy could possibily void that need.

Regarding downsides: post-install updates would indeed need to be made with updating the whole environment, while for now that can be 2 separate processes. But is it wise ? Shouldn't the environment version refer to both the tarball and the postinstall, which anyway are closely linked ? (postinstall is to be adapted to the OS used in the environment and work anywhere in G5K where the environment is used).

Regarding the last point: what check currently do kadeploy, if as a user I would use my own buggy postinstall, which would have nothing to do with the one of the staff provided environment ?

**Comment by npf** [comment]
Inviting @ejeanvoi to this thread, since we discussed together some time ago the merge between prepost and kadeploy provided info (e.g. ttys, partitions, etc), and the definition of a new clean interface (the current prepost interface dates back to kadeploy 2, if I am correct).

**Comment by SimonDelamare** [comment]
> Regarding downsides: post-install updates would indeed need to be made with updating the whole
> environment, while for now that can be 2 separate processes. But is it wise ? Shouldn't the environment
> version refer to both the tarball and the postinstall, which anyway are closely linked ? (postinstall is to be
> adapted to the OS used in the environment and work anywhere in G5K where the environment is used).

Note that this is already the case (and it seems fine to me): As postinstall path (including its version) is declared inside kameleon-g5k/virtualbox/jessie-x64-X.yaml, a postinstall update requires modifying the environment recipe, thus release a new environment.

**Comment by dmargery** [comment]
Le 04/03/2016 15:25, SimonDelamare a écrit :

> ```
> Regarding downsides: post-install updates would indeed need to be
> made with updating the whole
> environment, while for now that can be 2 separate processes. But is
> it wise ? Shouldn't the environment
> version refer to both the tarball and the postinstall, which anyway
> are closely linked ? (postinstall is to be
> adapted to the OS used in the environment and work anywhere in G5K
> where the environment is used).
> ```
> 
> Note that this is already the case (and it seems fine to me): As
> postinstall path (including its version) is declared inside
> kameleon-g5k/virtualbox/jessie-x64-X.yaml, a postinstall update requires
> modifying the environment recipe, thus release a new environment.

The questions I have remain : if an update of the post-install was
required, and the post-install is embedded in the environement,
- what update path for previously generated environements ?
- how to help users discover that they are missing an update to their
  post-install and that they need to use the update path ?

David

## 

David Margery <><   (jabber/mail:David.Margery@inria.fr)
Ingénieur de Recherche
Directeur technique de Grid'5000
Centre de recherche INRIA Rennes - Bretagne Atlantique, France
Equipe Myriads, bureau E201, niveau vert, tel +33 2 99 84 25 12

**Comment by dmargery** [comment]
Le 04/03/2016 14:30, Pierre Neyron a écrit :

> Regarding the last point: what check currently do kadeploy, if as a user
> I would use my own buggy postinstall, which would have nothing to do
> with the one of the staff provided environment ?

None.

But I can imagine that if the md5sum of your post-install matches the
md5sum of a known post-install, this means that you are relying only on
the provided post-install, and that you might want it updated for you,
or at least notified that you are using an outdated post-install.

David

## 

David Margery <><   (jabber/mail:David.Margery@inria.fr)
Ingénieur de Recherche
Directeur technique de Grid'5000
Centre de recherche INRIA Rennes - Bretagne Atlantique, France
Equipe Myriads, bureau E201, niveau vert, tel +33 2 99 84 25 12

**Comment by npf** [comment]
Note:
 -  recipes now use the g5k-postinstall mechanism.
 - the generation produce the env dsc now.
 - projects is moved to gitlab.inria.
